# Generated by Django 3.2 on 2023-09-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
