name: chat-app-deploy CI
on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzP --delete
        path: src/*
        remote_path: /home/devil/chatapp_backend
        remote_host: ${{ secrets.DEPLOY_SERVER_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        
